import type { Session, SessionEvent } from '@srgnt/contracts';

/**
 * Pure markdown renderer for a session's `events.jsonl` (STEP-24-05).
 *
 * `transcript.md` is a DERIVED CACHE, never a second source of truth: nothing
 * is rendered here that is not already in the log, so the file can be deleted
 * at any moment and regenerated byte-identically from `events.jsonl` + the
 * session's `meta.json`. That is what lets checkpoints be lossy — a checkpoint
 * missed by a crash costs no session content, because reopening re-renders.
 *
 * Two properties are load-bearing and property-tested:
 *
 * 1. **Deterministic.** No clock, no locale, no randomness. Same
 *    `(events, meta)` → same bytes, on every machine and every run.
 * 2. **Tolerant (ARCH-0009).** Unknown `kind` values, unknown ACP
 *    `sessionUpdate` kinds, and malformed payloads are skipped, never thrown
 *    on. A transcript that refuses to render is strictly worse than one missing
 *    a line nobody can parse.
 *
 * Recorded assumption (from the Execution Brief): agent *thoughts* are
 * summarized as a count rather than inlined. Transcripts exist for humans and
 * memsearch, not verbatim replay — the log keeps the full data either way.
 */

/** Extra context the log itself cannot carry. */
export interface RenderTranscriptOptions {
  /**
   * The log did not end on a record boundary (crash mid-append). Adds the
   * interrupted marker; the session's own `interrupted` status does the same.
   */
  readonly truncatedTail?: boolean;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null;
}

function asString(value: unknown): string | undefined {
  return typeof value === 'string' && value !== '' ? value : undefined;
}

/**
 * Unwraps the body of a persisted `acp/session_update` payload. Accepts the
 * full notification (`{sessionId, update}`) and the bare update body, for the
 * same reason the renderer's `transcriptReducer` does: both shapes reach us
 * depending on how the frame was constructed.
 */
function updateBody(payload: unknown): Record<string, unknown> | undefined {
  if (!isRecord(payload)) return undefined;
  const inner = payload['update'];
  if (isRecord(inner) && typeof inner['sessionUpdate'] === 'string') return inner;
  if (typeof payload['sessionUpdate'] === 'string') return payload;
  return undefined;
}

/** Text out of an ACP content block. Non-text blocks contribute nothing. */
function chunkText(body: Record<string, unknown>): string | undefined {
  const content = body['content'];
  if (!isRecord(content) || content['type'] !== 'text') return undefined;
  return typeof content['text'] === 'string' ? content['text'] : undefined;
}

/** Collapses whitespace so a multi-line title stays one markdown line. */
function oneLine(text: string): string {
  return text.replace(/\s+/g, ' ').trim();
}

/** A tool call, mutated in place by every later `tool_call_update`. */
interface ToolBlock {
  readonly kind: 'tool';
  readonly id: string;
  title: string;
  toolKind: string | undefined;
  status: string;
}

type Block =
  | { readonly kind: 'user' | 'agent'; text: string }
  | { readonly kind: 'note'; readonly text: string }
  | ToolBlock;

interface Turn {
  readonly blocks: Block[];
  thoughts: number;
  stop: string | undefined;
}

function newTurn(): Turn {
  return { blocks: [], thoughts: 0, stop: undefined };
}

function isEmpty(turn: Turn): boolean {
  return turn.blocks.length === 0 && turn.thoughts === 0 && turn.stop === undefined;
}

/**
 * Appends text, coalescing consecutive agent chunks into the trailing block
 * exactly as the live reducer does — so `message → tool → message` renders as
 * two message blocks with the tool line between them, never one merged block.
 */
function appendText(turn: Turn, kind: 'user' | 'agent', text: string): void {
  const last = turn.blocks[turn.blocks.length - 1];
  if (last !== undefined && last.kind === kind) {
    last.text += text;
    return;
  }
  turn.blocks.push({ kind, text });
}

function renderTool(block: ToolBlock): string {
  const kind = block.toolKind === undefined ? '' : `(${block.toolKind}) `;
  return `- Tool ${kind}**${block.title}** — ${block.status}`;
}

/**
 * Renders one session as markdown.
 *
 * `events` must be in log order (the store returns them that way); `meta` is
 * the session's `meta.json`. Neither is mutated.
 */
export function renderTranscript(
  events: readonly SessionEvent[],
  meta: Session,
  options: RenderTranscriptOptions = {}
): string {
  // Turns are collected first and rendered last, so a `tool_call_update` that
  // lands after its turn ended still updates the call's status rather than
  // being written into markdown nobody can edit any more.
  const turns: Turn[] = [];
  let turn = newTurn();
  const toolsById = new Map<string, ToolBlock>();

  const endTurn = (): void => {
    if (isEmpty(turn)) return;
    turns.push(turn);
    turn = newTurn();
  };

  for (const event of events) {
    const payload = event.payload;
    switch (event.kind) {
      case 'client/prompt': {
        // A prompt opens a turn: anything buffered before it belongs to the
        // previous one (a turn that never reported a stop reason).
        endTurn();
        appendText(turn, 'user', (isRecord(payload) ? asString(payload['text']) : undefined) ?? '(empty prompt)');
        break;
      }
      case 'client/stop': {
        const stop = isRecord(payload) ? asString(payload['stopReason']) : undefined;
        const message = isRecord(payload) ? asString(payload['message']) : undefined;
        turn.stop = message === undefined ? (stop ?? 'unknown') : `${stop ?? 'error'} - ${message}`;
        endTurn();
        break;
      }
      case 'client/permission_decision': {
        if (!isRecord(payload)) break;
        const title = asString(payload['title']) ?? asString(payload['toolCallId']) ?? 'request';
        const outcome =
          asString(payload['optionId']) ??
          asString(payload['outcome']) ??
          asString(payload['reason']) ??
          'answered';
        turn.blocks.push({ kind: 'note', text: `- Permission **${title}** -> ${outcome}` });
        break;
      }
      case 'client/fs_read_text_file':
      case 'client/fs_write_text_file':
      case 'client/fs_denied': {
        if (!isRecord(payload)) break;
        const path = asString(payload['path']);
        if (path === undefined) break;
        const verb =
          event.kind === 'client/fs_denied'
            ? 'denied'
            : event.kind === 'client/fs_write_text_file'
              ? 'wrote'
              : 'read';
        turn.blocks.push({ kind: 'note', text: `- Client ${verb} \`${path}\`` });
        break;
      }
      case 'client/reconnected': {
        const via = isRecord(payload) ? asString(payload['via']) : undefined;
        turn.blocks.push({
          kind: 'note',
          text: `- Reconnected${via === undefined ? '' : ` via \`${via}\``}`,
        });
        break;
      }
      case 'client/harness_reaped':
        turn.blocks.push({
          kind: 'note',
          text: '- Agent process reaped for idleness (session is resumable)',
        });
        break;
      case 'client/agent_status': {
        if (!isRecord(payload)) break;
        const status = asString(payload['status']);
        // Only failures earn a transcript line; spawning/ready/exited are
        // transport detail the log already keeps in full.
        if (status !== 'crashed' && status !== 'gave-up') break;
        turn.blocks.push({
          kind: 'note',
          text: `- Agent process ${status}: ${asString(payload['message']) ?? 'no detail'}`,
        });
        break;
      }
      case 'client/session_closed':
        endTurn();
        turn.blocks.push({ kind: 'note', text: '- Session closed' });
        break;
      case 'acp/session_update': {
        const body = updateBody(payload);
        if (body === undefined) break;
        switch (body['sessionUpdate']) {
          case 'agent_thought_chunk':
            turn.thoughts += 1;
            break;
          case 'agent_message_chunk':
          case 'user_message_chunk': {
            const text = chunkText(body);
            if (text === undefined || text === '') break;
            appendText(turn, body['sessionUpdate'] === 'agent_message_chunk' ? 'agent' : 'user', text);
            break;
          }
          case 'tool_call':
          case 'tool_call_update': {
            const id = asString(body['toolCallId']);
            if (id === undefined) break;
            const existing = toolsById.get(id);
            if (existing !== undefined) {
              // Per spec an update carries the full record; absent fields keep
              // what the opening frame said.
              existing.title = asString(body['title']) ?? existing.title;
              existing.toolKind = asString(body['kind']) ?? existing.toolKind;
              existing.status = asString(body['status']) ?? existing.status;
              break;
            }
            // An update whose opening frame never arrived is still evidence of
            // agent activity — rendered rather than dropped.
            const block: ToolBlock = {
              kind: 'tool',
              id,
              title: asString(body['title']) ?? id,
              toolKind: asString(body['kind']),
              status: asString(body['status']) ?? 'pending',
            };
            turn.blocks.push(block);
            toolsById.set(id, block);
            break;
          }
          default:
            // plan / mode / commands / anything the protocol grows after us:
            // deliberately not rendered.
            break;
        }
        break;
      }
      default:
        // Unknown envelope kind: skipped, never thrown on.
        break;
    }
  }
  endTurn();

  const lines: string[] = [`# ${oneLine(meta.title ?? meta.id)}`, ''];
  lines.push(`- Session: \`${meta.id}\``);
  lines.push(`- Project: \`${meta.projectId}\``);
  lines.push(`- Harness: ${meta.harnessId}`);
  lines.push(`- Status: ${meta.status}`);
  lines.push(`- Created: ${meta.createdAt}`);
  if (meta.updatedAt !== undefined) lines.push(`- Updated: ${meta.updatedAt}`);
  if (meta.parentSessionId !== undefined) lines.push(`- Forked from: \`${meta.parentSessionId}\``);
  lines.push('');

  turns.forEach((entry, index) => {
    lines.push(`## Turn ${String(index + 1)}`, '');
    for (const block of entry.blocks) {
      switch (block.kind) {
        case 'user':
          lines.push('**User**', '', block.text.trimEnd(), '');
          break;
        case 'agent':
          lines.push('**Agent**', '', block.text.trimEnd(), '');
          break;
        case 'tool':
          lines.push(renderTool(block), '');
          break;
        default:
          lines.push(block.text, '');
      }
    }
    if (entry.thoughts > 0) {
      lines.push(`_${String(entry.thoughts)} thought chunk${entry.thoughts === 1 ? '' : 's'}_`, '');
    }
    if (entry.stop !== undefined) lines.push(`_Stopped: ${entry.stop}_`, '');
  });

  if (turns.length === 0) lines.push('_No turns recorded._', '');
  if (options.truncatedTail === true || meta.status === 'interrupted') {
    lines.push('_... interrupted: the session ended before its last turn completed._', '');
  }

  // Exactly one trailing newline, whatever the last block was.
  return `${lines.join('\n').replace(/\n+$/, '')}\n`;
}
