import type { Task, Event, Message, Artifact } from '../entities/index.js';
import { Schema } from "@effect/schema";

const datetimePattern = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d{3})?Z$/;

export const STodayWorkflowInput = Schema.Struct({
  date: Schema.String.pipe(Schema.pattern(datetimePattern)),
  includeTasks: Schema.optionalWith(Schema.Boolean, { default: () => true }),
  includeCalendar: Schema.optionalWith(Schema.Boolean, { default: () => true }),
  includeMessages: Schema.optionalWith(Schema.Boolean, { default: () => true }),
});

export type TodayWorkflowInput = Schema.Schema.Type<typeof STodayWorkflowInput>;

export const STodayWorkflowBriefing = Schema.Struct({
  date: Schema.String.pipe(Schema.pattern(datetimePattern)),
  summary: Schema.String,
  tasks: Schema.optionalWith(Schema.Array(Schema.String), { default: () => [] }),
  events: Schema.optionalWith(Schema.Array(Schema.String), { default: () => [] }),
  messages: Schema.optionalWith(Schema.Array(Schema.String), { default: () => [] }),
  actionItems: Schema.optionalWith(Schema.Array(Schema.String), { default: () => [] }),
  blockers: Schema.optionalWith(Schema.Array(Schema.String), { default: () => [] }),
});

export const STodayWorkflowOutput = Schema.Struct({
  briefing: STodayWorkflowBriefing,
  artifacts: Schema.optionalWith(Schema.Array(Schema.String), { default: () => [] }),
});

export type TodayWorkflowOutput = Schema.Schema.Type<typeof STodayWorkflowOutput>;

export interface DailyBriefingData {
  tasks: Task[];
  events: Event[];
  messages: Message[];
}

export function generateBriefingContent(data: DailyBriefingData, date: string): string {
  const lines: string[] = [
    `# Daily Briefing - ${new Date(date).toLocaleDateString()}`,
    '',
    '## Summary',
    `Today you have ${data.events.length} meetings and ${data.tasks.filter((t) => t.status !== 'done').length} open tasks.`,
    '',
  ];

  if (data.tasks.length > 0) {
    lines.push('## Tasks');
    for (const task of data.tasks) {
      const status = task.status === 'done' ? '[x]' : '[ ]';
      const priority = task.priority ? ` [${task.priority}]` : '';
      lines.push(`- ${status} ${task.title}${priority}`);
    }
    lines.push('');
  }

  if (data.events.length > 0) {
    lines.push('## Calendar');
    for (const event of data.events) {
      const time = new Date(event.startTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
      lines.push(`- ${time} - ${event.title}`);
      if (event.location) {
        lines.push(`  Location: ${event.location}`);
      }
    }
    lines.push('');
  }

  if (data.messages.length > 0) {
    lines.push('## Messages');
    for (const message of data.messages.slice(0, 5)) {
      lines.push(`- From: ${message.sender} - ${message.subject || message.body.slice(0, 50)}...`);
    }
    if (data.messages.length > 5) {
      lines.push(`- ... and ${data.messages.length - 5} more messages`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by srgnt*');

  return lines.join('\n');
}

export function createBriefingArtifact(
  data: DailyBriefingData,
  date: string
): Artifact {
  const content = generateBriefingContent(data, date);
  return {
    envelope: {
      id: `briefing-${date}`,
      canonicalType: 'Artifact',
      provider: 'srgnt',
    },
    name: `Daily Briefing - ${new Date(date).toLocaleDateString()}`,
    content,
    contentType: 'markdown',
    sourceSkill: 'daily-briefing',
    createdAt: new Date().toISOString(),
    tags: ['daily', 'briefing'],
  };
}
