import { describe, it, expect } from 'vitest';
import { parseSync } from '../shared-schemas.js';
import {
  STodayWorkflowInput,
  STodayWorkflowBriefing,
  STodayWorkflowOutput,
  generateBriefingContent,
  createBriefingArtifact,
} from './daily-briefing.js';
import type { Task, Event, Message } from '../entities/index.js';

// --- helpers ---

const validDate = '2026-04-12T09:00:00Z';
const expectedDisplayDate = new Date(validDate).toLocaleDateString();

function makeTask(overrides: Partial<Task> & { title: string }): Task {
  return {
    envelope: { id: 't-1', canonicalType: 'Task' },
    title: overrides.title,
    ...overrides,
  } as Task;
}

function makeEvent(overrides: Partial<Event> & { title: string; startTime: string }): Event {
  return {
    envelope: { id: 'e-1', canonicalType: 'Event' },
    title: overrides.title,
    startTime: overrides.startTime,
    ...overrides,
  } as Event;
}

function makeMessage(overrides: Partial<Message> & { body: string; sender: string; sentAt: string }): Message {
  return {
    envelope: { id: 'm-1', canonicalType: 'Message' },
    body: overrides.body,
    sender: overrides.sender,
    sentAt: overrides.sentAt,
    ...overrides,
  } as Message;
}

// --- STodayWorkflowInput ---

describe('STodayWorkflowInput', () => {
  it('validates minimal input (date only)', () => {
    const input = { date: validDate };
    const result = parseSync(STodayWorkflowInput, input);
    expect(result.date).toBe(validDate);
  });

  it('defaults includeTasks, includeCalendar, includeMessages to true', () => {
    const input = { date: validDate };
    const result = parseSync(STodayWorkflowInput, input);
    expect(result.includeTasks).toBe(true);
    expect(result.includeCalendar).toBe(true);
    expect(result.includeMessages).toBe(true);
  });

  it('rejects invalid date format', () => {
    expect(() => parseSync(STodayWorkflowInput, { date: '2026/04/12' })).toThrow();
    expect(() => parseSync(STodayWorkflowInput, { date: 'not-a-date' })).toThrow();
  });
});

// --- STodayWorkflowBriefing ---

describe('STodayWorkflowBriefing', () => {
  it('validates minimal briefing (date + summary)', () => {
    const result = parseSync(STodayWorkflowBriefing, {
      date: validDate,
      summary: 'You have a light day.',
    });
    expect(result.date).toBe(validDate);
    expect(result.summary).toBe('You have a light day.');
  });

  it('defaults all array fields to []', () => {
    const result = parseSync(STodayWorkflowBriefing, {
      date: validDate,
      summary: 'A day.',
    });
    expect(result.tasks).toEqual([]);
    expect(result.events).toEqual([]);
    expect(result.messages).toEqual([]);
    expect(result.actionItems).toEqual([]);
    expect(result.blockers).toEqual([]);
  });

  it('validates full briefing with all fields', () => {
    const result = parseSync(STodayWorkflowBriefing, {
      date: validDate,
      summary: 'Busy day.',
      tasks: ['Review PR'],
      events: ['Standup'],
      messages: ['From Alice'],
      actionItems: ['Ship feature'],
      blockers: ['Waiting on API'],
    });
    expect(result.tasks).toEqual(['Review PR']);
    expect(result.actionItems).toEqual(['Ship feature']);
  });
});

// --- STodayWorkflowOutput ---

describe('STodayWorkflowOutput', () => {
  it('validates minimal output (briefing only)', () => {
    const result = parseSync(STodayWorkflowOutput, {
      briefing: { date: validDate, summary: 'OK' },
    });
    expect(result.briefing.summary).toBe('OK');
  });

  it('defaults artifacts to []', () => {
    const result = parseSync(STodayWorkflowOutput, {
      briefing: { date: validDate, summary: 'OK' },
    });
    expect(result.artifacts).toEqual([]);
  });
});

// --- generateBriefingContent ---

describe('generateBriefingContent', () => {
  it('generates markdown with correct heading and summary', () => {
    const content = generateBriefingContent({ tasks: [], events: [], messages: [] }, validDate);
    expect(content).toContain('# Daily Briefing');
    expect(content).toContain('0 meetings and 0 open tasks');
    expect(content).toContain('Generated by srgnt');
  });

  it('includes tasks section when tasks present, with correct checkbox status', () => {
    const tasks = [
      makeTask({ title: 'Open task', status: 'open', priority: 'high', envelope: { id: 't-1', canonicalType: 'Task' } }),
      makeTask({ title: 'Done task', status: 'done', envelope: { id: 't-2', canonicalType: 'Task' } }),
    ];
    const content = generateBriefingContent({ tasks, events: [], messages: [] }, validDate);
    expect(content).toContain('## Tasks');
    expect(content).toContain('[ ] Open task [high]');
    expect(content).toContain('[x] Done task');
  });

  it('includes calendar section when events present, with time formatting', () => {
    const events = [
      makeEvent({ title: 'Standup', startTime: '2026-04-12T09:30:00Z', location: 'Zoom', envelope: { id: 'e-1', canonicalType: 'Event' } }),
    ];
    const content = generateBriefingContent({ tasks: [], events, messages: [] }, validDate);
    expect(content).toContain('## Calendar');
    expect(content).toContain('Standup');
    expect(content).toContain('Location: Zoom');
  });

  it('includes messages section when messages present, truncates at 5', () => {
    const messages = Array.from({ length: 7 }, (_, i) =>
      makeMessage({
        body: `Message body ${i}`,
        sender: `sender${i}@example.com`,
        sentAt: '2026-04-12T08:00:00Z',
        subject: `Subject ${i}`,
        envelope: { id: `m-${i}`, canonicalType: 'Message' },
      })
    );
    const content = generateBriefingContent({ tasks: [], events: [], messages }, validDate);
    expect(content).toContain('## Messages');
    expect(content).toContain('From: sender0@example.com - Subject 0...');
    expect(content).toContain('From: sender4@example.com - Subject 4...');
    expect(content).toContain('and 2 more messages');
    expect(content).not.toContain('Subject 5');
  });

  it('handles empty data — only heading, summary, and footer', () => {
    const content = generateBriefingContent({ tasks: [], events: [], messages: [] }, validDate);
    const lines = content.split('\n').filter((l) => l.trim() !== '');
    expect(lines).toEqual([
      `# Daily Briefing - ${expectedDisplayDate}`,
      '## Summary',
      'Today you have 0 meetings and 0 open tasks.',
      '---',
      '*Generated by srgnt*',
    ]);
  });
});

// --- createBriefingArtifact ---

describe('createBriefingArtifact', () => {
  it('returns an artifact with correct structure', () => {
    const data: import('./daily-briefing.js').DailyBriefingData = {
      tasks: [],
      events: [],
      messages: [],
    };
    const artifact = createBriefingArtifact(data, validDate);
    expect(artifact.envelope.id).toBe(`briefing-${validDate}`);
    expect(artifact.envelope.canonicalType).toBe('Artifact');
    expect(artifact.envelope.provider).toBe('srgnt');
    expect(artifact.contentType).toBe('markdown');
    expect(artifact.sourceSkill).toBe('daily-briefing');
    expect(artifact.tags).toEqual(['daily', 'briefing']);
    expect(artifact.name).toContain('Daily Briefing');
    expect(artifact.content).toContain('# Daily Briefing');
  });

  it('content matches generateBriefingContent output for same input', () => {
    const data: import('./daily-briefing.js').DailyBriefingData = {
      tasks: [makeTask({ title: 'Test', envelope: { id: 't-1', canonicalType: 'Task' } })],
      events: [],
      messages: [],
    };
    const artifact = createBriefingArtifact(data, validDate);
    const expected = generateBriefingContent(data, validDate);
    expect(artifact.content).toBe(expected);
  });
});
